# German translations for vigilo-connector.
# Copyright (C) 2010 ORGANIZATION
# This file is distributed under the same license as the vigilo-connector
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version: vigilo-connector 2.0.0\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-11-19 12:16+0100\n"
"PO-Revision-Date: 2011-10-03 10:34+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: de <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/connector/client.py:66
msgid "'require_compression' cannot be True when 'require_tls' is also True."
msgstr ""

#: src/vigilo/connector/client.py:107 src/vigilo/connector/client.py:456
msgid "Some error occurred while negotiating TLS encryption"
msgstr ""

#: src/vigilo/connector/client.py:109 src/vigilo/connector/client.py:458
msgid ""
"The server requires TLS encryption. Use the 'require_tls' option to "
"enable TLS encryption."
msgstr ""

#: src/vigilo/connector/client.py:112 src/vigilo/connector/client.py:461
msgid "TLS encryption was required, but pyOpenSSL is not installed"
msgstr ""

#: src/vigilo/connector/client.py:117
#, python-format
msgid "Authentication failure: %s"
msgstr ""

#: src/vigilo/connector/client.py:136 src/vigilo/connector/client.py:483
#, python-format
msgid "The server does not support the '%s' feature"
msgstr ""

#: src/vigilo/connector/client.py:223
msgid ""
"The \"watched_topics\" option has now been renamed into "
"\"subscriptions\". Please update your configuration file."
msgstr ""

#: src/vigilo/connector/client.py:259
#, python-format
msgid "Server %(oldserver)s did not answer after %(attempts)d attempts"
msgstr ""

#: src/vigilo/connector/client.py:386
#, python-format
msgid "Creating lock file in %s"
msgstr ""

#: src/vigilo/connector/client.py:396
#, python-format
msgid ""
"Found a lock file, but the following exception was raised when trying to "
"open it: %s. Cowardly exiting..."
msgstr ""

#: src/vigilo/connector/client.py:404
#, python-format
msgid ""
"Another instance of this connector is already running (PID: %s). "
"Exiting..."
msgstr ""

#: src/vigilo/connector/client.py:412
#, python-format
msgid ""
"Found a lock file, but no process is running with this PID (%s). Removing"
" it..."
msgstr ""

#: src/vigilo/connector/client.py:428
#, python-format
msgid ""
"The following exception was raised when trying to create the lock file: "
"%s. Cowardly exiting..."
msgstr ""

#: src/vigilo/connector/client.py:437
#, python-format
msgid "Lock file successfully created in %s"
msgstr ""

#: src/vigilo/connector/client.py:448
#, python-format
msgid "Removing lock file (%s)"
msgstr ""

#: src/vigilo/connector/client.py:466
msgid "Timeout"
msgstr ""

#: src/vigilo/connector/client.py:469
#, python-format
msgid "Authentication failed: %s"
msgstr ""

#: src/vigilo/connector/client.py:498
#, python-format
msgid "Error: %(message)s (%(type)r)"
msgstr ""

#: src/vigilo/connector/client.py:504
msgid "Exiting with no error"
msgstr ""

#: src/vigilo/connector/client.py:572
msgid "No handler registered for this one-shot XMPP client"
msgstr ""

#: src/vigilo/connector/converttoxml.py:57
#: src/vigilo/connector/converttoxml.py:64
#: src/vigilo/connector/converttoxml.py:70
#, python-format
msgid "Unknown/malformed message type: '%s'"
msgstr "Unbekannter/fehlerhafter Nachrichtentyp: '%s'"

#: src/vigilo/connector/converttoxml.py:74
#, python-format
msgid "Got malformed message: %s"
msgstr "Fehlerhafte Nachricht: %s vorhanden"

#: src/vigilo/connector/forwarder.py:35
msgid "no connection"
msgstr ""

#: src/vigilo/connector/forwarder.py:39
msgid "no connection to the XMPP server"
msgstr ""

#: src/vigilo/connector/forwarder.py:113
#, python-format
msgid ""
"Can't understand the max_queue_size option, it should be an integer (or 0"
" for no limit). Current value: %s"
msgstr ""

#: src/vigilo/connector/forwarder.py:121
msgid "The max_queue_size option is only available on Python >= 2.6. Ignoring."
msgstr ""

#: src/vigilo/connector/forwarder.py:158
#, python-format
msgid "Lost connection to the XMPP bus (reason: %s)"
msgstr ""

#: src/vigilo/connector/forwarder.py:190
#, python-format
msgid "Unable to forward the message (%(reason)s)"
msgstr ""

#: src/vigilo/connector/forwarder.py:196
msgid ". it has been stored for later retransmission"
msgstr ". Wird gespeichert und später erneut gesendet"

#: src/vigilo/connector/forwarder.py:209
#, python-format
msgid "Queue size too high (%s) ! Pausing reception"
msgstr ""

#: src/vigilo/connector/forwarder.py:276
#, python-format
msgid "Batch sent, waiting for %d replies from the bus"
msgstr ""

#: src/vigilo/connector/forwarder.py:293
#, python-format
msgid "Error trying to save a message to the backup database: %s"
msgstr ""

#: src/vigilo/connector/forwarder.py:485
#, python-format
msgid "No destination node configured for messages of type '%s'. Skipping."
msgstr "Kein Zielknoten für Nachrichten vom Typ '%s' konfiguriert. Überspringen."

#: src/vigilo/connector/main.py:42
#, python-format
msgid "Directory not found: '%(dir)s'"
msgstr "Verzeichnis: '%(dir)s' nicht gefunden"

#: src/vigilo/connector/main.py:47
#, python-format
msgid "Directory not readable: '%(dir)s'"
msgstr "Verzeichnis: '%(dir)s' nicht lesbar"

#: src/vigilo/connector/main.py:52
#, python-format
msgid "Directory not writable: '%(dir)s'"
msgstr "Verzeichnis: '%(dir)s' nicht überschreibbar"

#: src/vigilo/connector/main.py:57
#, python-format
msgid "Directory not executable: '%(dir)s'"
msgstr "Verzeichnis: '%(dir)s' nicht ausführbar"

#: src/vigilo/connector/nodetoqueuefw.py:62
msgid "Incoming message is too big to be stored in the queue, dropping it."
msgstr ""
"Eingehende Nachricht ist zu groß, um in der Warteschlange gespeichert zu "
"werden, abbrechen."

#: src/vigilo/connector/nodetoqueuefw.py:67
#, python-format
msgid "The queue is full, dropping incoming XML message! (%s)"
msgstr ""
"Die Warteschlange ist voll, eingehende XML Nachricht wird abgebrochen! "
"(%s)"

#: src/vigilo/connector/nodetosocketfw.py:26
msgid "socket not connected"
msgstr ""

#: src/vigilo/connector/options.py:13
msgid "Choose the service name"
msgstr ""

#: src/vigilo/connector/options.py:14
msgid "Load this settings.ini file"
msgstr ""

#: src/vigilo/connector/options.py:25
msgid "The configuration file does not exist"
msgstr ""

#: src/vigilo/connector/presence.py:63
msgid "Invalid value for setting bus/priority: it must be an integer"
msgstr ""

#: src/vigilo/connector/presence.py:70
msgid "Connected to the XMPP bus"
msgstr "Mit XMPP-Bus verbunden"

#: src/vigilo/connector/presence.py:131
msgid ""
"I wanted to become master, but the priority is already taken. This should"
" not happen."
msgstr ""

#: src/vigilo/connector/presence.py:237
#, python-format
msgid "Priority conflict, resetting priorities (%s)"
msgstr ""

#: src/vigilo/connector/queuetonodefw.py:86
msgid "Received request to shutdown"
msgstr "Anforderung zum Herunterfahren erhalten "

#: src/vigilo/connector/queuetonodefw.py:91
msgid "Item is None in consumeQueue, this should never happen!"
msgstr "Element ist Keine in consumeQueue, dies sollte nie  vorkommen!"

#: src/vigilo/connector/queuetonodefw.py:96
msgid "Stopping QueueToNodeForwarder."
msgstr "WarteschlangeToNodeForwarder beendet."

#: src/vigilo/connector/sockettonodefw.py:44
#, python-format
msgid "Unparsable line: %s"
msgstr ""

#: src/vigilo/connector/status.py:65 src/vigilo/connector/status.py:139
msgid "OK: running"
msgstr ""

#: src/vigilo/connector/status.py:129
#, python-format
msgid "Stats for %(service)s: %(name)s = %(value)s"
msgstr ""

#: src/vigilo/connector/status.py:135
msgid "WARNING: queue full"
msgstr ""

#: src/vigilo/connector/store.py:181 src/vigilo/connector/store.py:276
#, python-format
msgid "Could not fill the output buffer: %s"
msgstr ""

#: src/vigilo/connector/store.py:221
#, python-format
msgid "Could not VACUUM the database: %s"
msgstr ""

