# French translations for PACKAGE package
# Traductions françaises du paquet PACKAGE.
# Copyright (C) 2010 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Automatically generated, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version:  vigilo.connector\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-04-23 16:00+0200\n"
"PO-Revision-Date: 2011-10-03 10:34+0200\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: fr_FR <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/connector/client.py:66
msgid "'require_compression' cannot be True when 'require_tls' is also True."
msgstr ""
"'require_compression' ne peut valoir True lorsque 'require_tls' vaut \"\n"
"\"également True."

#: src/vigilo/connector/client.py:107 src/vigilo/connector/client.py:456
msgid "Some error occurred while negotiating TLS encryption"
msgstr "Une erreur est survenue lors de la négociation du chiffrement par TLS"

#: src/vigilo/connector/client.py:109 src/vigilo/connector/client.py:458
msgid ""
"The server requires TLS encryption. Use the 'require_tls' option to "
"enable TLS encryption."
msgstr ""
"Le serveur requiert un chiffrement par TLS. Utilisez l'option "
"'require_tls' pour activer le chiffrement."

#: src/vigilo/connector/client.py:112 src/vigilo/connector/client.py:461
msgid "TLS encryption was required, but pyOpenSSL is not installed"
msgstr "Le chiffrement par TLS est requis, mais pyOpenSSL n'est pas installé"

#: src/vigilo/connector/client.py:117
#, python-format
msgid "Authentication failure: %s"
msgstr "Échec de l'authentification : %s"

#: src/vigilo/connector/client.py:136 src/vigilo/connector/client.py:483
#, python-format
msgid "The server does not support the '%s' feature"
msgstr "Le serveur ne supporte pas la fonctionnalité '%s'."

#: src/vigilo/connector/client.py:223
msgid ""
"The \"watched_topics\" option has now been renamed into "
"\"subscriptions\". Please update your configuration file."
msgstr ""
"L'option \"watched_topics\" a été renommée en \"subscriptions\". Veuillez"
" mettre à jour votre fichier de configuration."

#: src/vigilo/connector/client.py:259
#, python-format
msgid "Server %(oldserver)s did not answer after %(attempts)d attempts"
msgstr "Le serveur %(oldserver)s n'a pas répondu après %(attempts)d tentatives"

#: src/vigilo/connector/client.py:386
#, python-format
msgid "Creating lock file in %s"
msgstr "Création d'un fichier de verrou dans %s"

#: src/vigilo/connector/client.py:396
#, python-format
msgid ""
"Found a lock file, but the following exception was raised when trying to "
"open it: %s. Cowardly exiting..."
msgstr ""
"Un fichier de verrou a été trouvé, mais l'exception suivante a été levée "
"lors de la tentative d'accès : %s. Abandon..."

#: src/vigilo/connector/client.py:404
#, python-format
msgid ""
"Another instance of this connector is already running (PID: %s). "
"Exiting..."
msgstr "Une autre instance de ce connecteur est déjà lancée (PID : %s). Sortie..."

#: src/vigilo/connector/client.py:412
#, python-format
msgid ""
"Found a lock file, but no process is running with this PID (%s). Removing"
" it..."
msgstr ""
"Un fichier de verrou a été trouvé, mais aucun processus n'est lancé avec "
"ce PID (%s). Suppression du verrou..."

#: src/vigilo/connector/client.py:428
#, python-format
msgid ""
"The following exception was raised when trying to create the lock file: "
"%s. Cowardly exiting..."
msgstr ""
"L'exception suivante a été levée durant la tentative de création du "
"fichier de verrou : %s. Abandon..."

#: src/vigilo/connector/client.py:437
#, python-format
msgid "Lock file successfully created in %s"
msgstr "Fichier de verrou créé avec succès dans %s"

#: src/vigilo/connector/client.py:448
#, python-format
msgid "Removing lock file (%s)"
msgstr "Suppression du fichier de verrou (%s)"

#: src/vigilo/connector/client.py:466
msgid "Timeout"
msgstr "Délai dépassé"

#: src/vigilo/connector/client.py:469
#, python-format
msgid "Authentication failed: %s"
msgstr "Échec de l'authentification : %s"

#: src/vigilo/connector/client.py:498
#, python-format
msgid "Error: %(message)s (%(type)r)"
msgstr "Erreur : %(message)s (%(type)r)"

#: src/vigilo/connector/client.py:504
msgid "Exiting with no error"
msgstr "Sortie sans erreur"

#: src/vigilo/connector/client.py:572
msgid "No handler registered for this one-shot XMPP client"
msgstr ""
"Aucune fonction de traitement n'a été enregistrée pour ce client XMPP "
"jetable"

#: src/vigilo/connector/converttoxml.py:57
#: src/vigilo/connector/converttoxml.py:64
#: src/vigilo/connector/converttoxml.py:70
#, python-format
msgid "Unknown/malformed message type: '%s'"
msgstr "Type de message inconnu ou message mal-formé: '%s'"

#: src/vigilo/connector/converttoxml.py:74
#, python-format
msgid "Got malformed message: %s"
msgstr "Réception d'un message mal-formé: %s"

#: src/vigilo/connector/forwarder.py:35
msgid "no connection"
msgstr "pas de connexion"

#: src/vigilo/connector/forwarder.py:39
msgid "no connection to the XMPP server"
msgstr "pas de connexion au serveur XMPP"

#: src/vigilo/connector/forwarder.py:113
#, python-format
msgid ""
"Can't understand the max_queue_size option, it should be an integer (or 0"
" for no limit). Current value: %s"
msgstr ""
"Impossible de lire l'option max_queue_size. Un nombre entier (ou 0 pour "
"supprimer la limite) doit être renseigné. Valeur actuelle : %s"

#: src/vigilo/connector/forwarder.py:121
msgid "The max_queue_size option is only available on Python >= 2.6. Ignoring."
msgstr "L'option max_queue_size n'est disponible que pour Python >= 2.6. Ignorée."

#: src/vigilo/connector/forwarder.py:158
#, python-format
msgid "Lost connection to the XMPP bus (reason: %s)"
msgstr "Connexion perdue au bus XMPP (raison : %s)"

#: src/vigilo/connector/forwarder.py:190
#, python-format
msgid "Unable to forward the message (%(reason)s)"
msgstr "Impossible de transmettre le message (%(reason)s)"

#: src/vigilo/connector/forwarder.py:196
msgid ". it has been stored for later retransmission"
msgstr ". Il a été sauvé pour une transmission ultérieure"

#: src/vigilo/connector/forwarder.py:209
#, python-format
msgid "Queue size too high (%s) ! Pausing reception"
msgstr "La taille de la file est trop élevée (%s) ! Mise en pause de la réception."

#: src/vigilo/connector/forwarder.py:276
#, python-format
msgid "Batch sent, waiting for %d replies from the bus"
msgstr "Groupe de message envoyé, en attente de %d confirmations du bus"

#: src/vigilo/connector/forwarder.py:293
#, python-format
msgid "Error trying to save a message to the backup database: %s"
msgstr ""
"Erreur lors de l'enregistrement du message en base de données de "
"sauvegarde : %s"

#: src/vigilo/connector/forwarder.py:485
#, python-format
msgid "No destination node configured for messages of type '%s'. Skipping."
msgstr "Aucun nœud cible configuré pour les messages de type '%s'. Message ignoré."

#: src/vigilo/connector/main.py:42
#, python-format
msgid "Directory not found: '%(dir)s'"
msgstr "Dossier non trouvé : '%(dir)s'"

#: src/vigilo/connector/main.py:47
#, python-format
msgid "Directory not readable: '%(dir)s'"
msgstr "Dossier inaccessible en lecture : '%(dir)s'"

#: src/vigilo/connector/main.py:52
#, python-format
msgid "Directory not writable: '%(dir)s'"
msgstr "Dossier inaccessible en écriture : '%(dir)s'"

#: src/vigilo/connector/main.py:57
#, python-format
msgid "Directory not executable: '%(dir)s'"
msgstr "Dossier inaccessible en exécution : '%(dir)s'"

#: src/vigilo/connector/nodetoqueuefw.py:62
msgid "Incoming message is too big to be stored in the queue, dropping it."
msgstr ""
"Le message entrant est trop volumineux pour être stocké, message \"\n"
"\"ignoré."

#: src/vigilo/connector/nodetoqueuefw.py:67
#, python-format
msgid "The queue is full, dropping incoming XML message! (%s)"
msgstr "La file est pleine, le message XML entrant a été ignoré! (%s)"

#: src/vigilo/connector/nodetosocketfw.py:26
msgid "socket not connected"
msgstr "socket non connecté"

#: src/vigilo/connector/options.py:13
msgid "Choose the service name"
msgstr "Choisir le nom du service"

#: src/vigilo/connector/options.py:14
msgid "Load this settings.ini file"
msgstr "Utiliser ce fichier settings.ini"

#: src/vigilo/connector/options.py:25
msgid "The configuration file does not exist"
msgstr "Le fichier de configuration n'existe pas"

#: src/vigilo/connector/presence.py:63
msgid "Invalid value for setting bus/priority: it must be an integer"
msgstr "Valeur non valide pour l'option bus/priority : un entier est attendu"

#: src/vigilo/connector/presence.py:70
msgid "Connected to the XMPP bus"
msgstr "Connecté au bus XMPP"

#: src/vigilo/connector/presence.py:131
msgid ""
"I wanted to become master, but the priority is already taken. This should"
" not happen."
msgstr ""
"Je voulais devenir le maître, mais la priorité est déjà prise. Ceci ne "
"devrait jamais arriver."

#: src/vigilo/connector/presence.py:237
#, python-format
msgid "Priority conflict, resetting priorities (%s)"
msgstr "Conflit de priorité détecté. Réinitialisation des priorités (%s)"

#: src/vigilo/connector/queuetonodefw.py:86
msgid "Received request to shutdown"
msgstr "Réception d'une demande d'arrêt"

#: src/vigilo/connector/queuetonodefw.py:91
msgid "Item is None in consumeQueue, this should never happen!"
msgstr "Objet None reçu dans consumeQueue, ça ne devrait jamais arriver !"

#: src/vigilo/connector/queuetonodefw.py:96
msgid "Stopping QueueToNodeForwarder."
msgstr "Arrêt de QueueToNodeForwarder."

#: src/vigilo/connector/sockettonodefw.py:44
#, python-format
msgid "Unparsable line: %s"
msgstr "Ligne illisible : %s"

#: src/vigilo/connector/status.py:65 src/vigilo/connector/status.py:139
msgid "OK: running"
msgstr "OK: en fonctionnement"

#: src/vigilo/connector/status.py:129
#, python-format
msgid "Stats for %(service)s: %(name)s = %(value)s"
msgstr "Statistiques pour %(service)s : %(name)s = %(value)s"

#: src/vigilo/connector/status.py:135
msgid "WARNING: queue full"
msgstr "WARNING: la file d'attente est pleine"

#: src/vigilo/connector/store.py:181 src/vigilo/connector/store.py:276
#, python-format
msgid "Could not fill the output buffer: %s"
msgstr "Impossible de remplir le tampon en sortie : %s"

#: src/vigilo/connector/store.py:221
#, python-format
msgid "Could not VACUUM the database: %s"
msgstr "Impossible de purger la base de données (VACUUM) : %s"

